DayDayFruit/DayDayFruit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from df_goods.views import index

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('Users.urls')),
    url(r'^$', index),
    url(r'^goods/', include('df_goods.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^order/', include('df_order.urls')),
]

DayDayFruit/Users/urls.py
from django.conf.urls import include, url
import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$', views.login),
    url(r'^login_handle/$', views.login_handle),
    url(r'^register/$', views.register),
    url(r'^register_handle/$', views.register_handle),
    url(r'^user_exit/$', views.user_exit),
    url(r'^user_center_info/$', views.user_center_info),
    url(r'^user_center_site/$', views.user_center_site),
    url(r'^logout/$', views.logout),
    url(r'^user_center_site_handle/$', views.user_center_site_handle),
    url(r'^user_center_order/$', views.user_center_order),
]

DayDayFruit/cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^display/$', views.display),
    url(r'^add/$', views.add),
    url(r'^calcNum/$', views.cart_count),
    url(r'^modify_num/$', views.modify_num),
    url(r'^modify/$', views.modify),
    url(r'^delete_cart/(\d+)/(\d+)/$', views.delete_cart),
    url(r'^cart_count/$', views.cart_count),
    url(r'^place_order/$', views.place_order),
]

DayDayFruit/Users/models.py
from django.db import models


# Create your models here.
class Users(models.Model):
    uname = models.CharField(max_length=20)
    pword = models.CharField(max_length=40)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20, default='')
    address = models.CharField(max_length=100, default='')
    contact = models.CharField(max_length=20, default='')
    postcode = models.CharField(max_length=6, default='')

    class Meta:
        db_table = 'Users'

    def __str__(self):
        return self.uname


class VisitInfo(models.Model):
    vpic = models.CharField(max_length=50)
    vtitle = models.CharField(max_length=20)
    vprice = models.DecimalField(max_digits=5, decimal_places=2)
    vunit = models.CharField(max_length=20,default='500g')
    vclick = models.IntegerField(default=1)
    vtype = models.IntegerField(default=1)
    vindex = models.IntegerField(default=1)
    vusers = models.ForeignKey(Users)

    class Meta:
        db_table = 'VisitInfo'

    def __str__(self):
        return self.vtitle

DayDayFruit/df_order/models.py
from django.db import models


# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('Users.Users')
    odate = models.DateTimeField(auto_now_add=True)
    oIsPay = models.BooleanField(default=False)
    oPayType = models.CharField(max_length=5, default='cash')
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    count = models.IntegerField(default=0)

DayDayFruit/Users/views.py
# coding:utf-8

from django.shortcuts import render, redirect
from models import *
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from . import user_decorator
from df_order.models import *


def index(request):
    return redirect('/goods/index/')


def login(request):
    context = {'uname_err_code': 0, 'pwd_err_code': 0}
    return render(request, 'Users/login.html', context)


# 注销用户
def logout(request):
    request.session.flush()
    return redirect('/user/login/')


def login_handle(request):
    from hashlib import sha1
    flage = True
    context = {}
    user = None

    if request.method == 'POST':
        dict = request.POST
        user_name = dict.get('username', '')
        pwd = dict.get('pwd')
        # 加密
        sha1 = sha1()
        sha1.update(pwd)
        pwd = sha1.hexdigest()
        rember_me = dict.get('rember_me', 0)

        # 检查用户名输入是否正确
        uname_err_code = check_user_for_login(user_name)
        if uname_err_code > 0:
            flage = False
            context['uname_err_code'] = uname_err_code
            context['uname'] = user_name
        else:
            context['uname_err_code'] = 0  # 正确返回0

        # 检查密码是否正确
        if user_name:
            if uname_err_code == 0:
                user = Users.objects.filter(uname=user_name)
                pword = user[0].pword
                if pword != pwd:
                    flage = False
                    context['pwd_err_code'] = 1
                else:
                    context['pwd_err_code'] = 0
            else:
                context['uname_err_code'] = 3
                context['pwd_err_code'] = 0
        else:
            context['uname_err_code'] = 1
            context['pwd_err_code'] = 0

        # 如果登陆成功跳转到首页，　否则返回错误信息
        if flage:
            url = request.COOKIES.get('url', '/user/')
            red = HttpResponseRedirect(url)
            # 成功后删除转向地址，防止以后直接登录造成的转向
            red.set_cookie('url', '', max_age=-1)

            if rember_me:
                red.set_cookie('uname', user_name)
            else:
                red.set_cookie('uname', '', max_age=-1)

            request.session['user_id'] = user[0].id
            request.session['user_name'] = user_name
            return red
            # return redirect('/user/')
        else:
            return render(request, 'Users/login.html', context)


# 渲染register页面
def register(request):
    context = {'uname_err_code': 0, 'pwd_err_code': 0}
    return render(request, 'Users/register.html', context)


# 检查用户是否存在，存在返回大于０
def user_exit(request):
    user_name = request.GET.get('user_name')
    count = Users.objects.filter(uname=user_name).count()
    return JsonResponse({'count': count})


# 用户注册
def register_handle(request):
    from hashlib import sha1
    flage = True
    context = {}

    if request.method == 'POST':
        # 获取输入的内容
        dict = request.POST
        user_name = dict.get('user_name')
        pwd = dict.get('pwd')
        cpwd = dict.get('cpwd')
        email = dict.get('email')

        # 检查用户名输入是否正确
        uname_err_code = check_user_name(user_name)
        if uname_err_code > 0:
            flage = False
            context['uname_err_code'] = uname_err_code
        else:
            context['uname_err_code'] = 0  # 正确返回0

        # 检查密码是否正确
        if pwd != cpwd:
            flage = False
            context['pwd_err_code'] = 1  # 错误返回１
        else:
            context['pwd_err_code'] = 0  # 正确返回0

        # 如果用户名和密码都正确，则提交到数据库
        if flage:
            user = Users()
            user.uname = user_name
            # 加密
            sha1 = sha1()
            sha1.update(pwd)
            pwd = sha1.hexdigest()

            user.pword = pwd
            user.email = email
            user.save()
            return redirect('/user/login/')
        else:
            # 否则将错误信息返回给前台页面
            return render(request, 'Users/register.html', context)


# 后台检查用户名是否正确
def check_user_name(user_name):
    if user_name == "":
        # "用户名不能为空！"
        return 1
    elif len(user_name) < 5 or len(user_name) > 20:
        # "用户名长度必须大于5且小于20！"
        return 2

    count = Users.objects.filter(uname=user_name).count()
    if count >= 1:
        # "用户名已经存在,请重新输入！"
        return 3
    else:
        return 0


def check_user_for_login(user_name):
    if user_name == "":
        # "用户名不能为空！"
        return 1
    elif len(user_name) < 5 or len(user_name) > 20:
        # "用户名长度必须大于5且小于20！"
        return 2

    count = Users.objects.filter(uname=user_name).count()
    if count == 0:
        return 3  # 用户不存在
    else:
        return 0


@user_decorator.login
def user_center_info(request):
    uname = ''
    phone = ''
    address = ''

    uid = request.session.get('user_id', 0)
    if uid:
        user = Users.objects.filter(id=uid)
        if user.count:
            uname = user[0].uname
            phone = user[0].phone
            address = user[0].address

        goods = VisitInfo.objects.filter(vusers_id=uid).order_by('-vclick')
        if goods.count <= 5:
            goods_list = goods
        else:
            goods_list = goods[0:5]
    context = {'uname': uname, 'phone': phone, 'address': address, 'page_num': 1, 'goods_list': goods_list,
               'title': '用户中心'}
    return render(request, 'Users/user_center_info.html', context)


@user_decorator.login
def user_center_site(request):
    contact = ''
    phone = ''
    address = ''
    postcode = ''

    uid = request.session.get('user_id', 0)
    if uid:
        user = Users.objects.filter(id=uid)
        if user.count:
            phone = user[0].phone
            address = user[0].address
            contact = user[0].contact
            postcode = user[0].postcode
    context = {'contact': contact, 'phone': phone, 'address': address, 'postcode': postcode, 'page_num': 1,
               'title': '用户中心'}
    return render(request, 'Users/user_center_site.html', context)


@user_decorator.login
def user_center_site_handle(request):
    uid = request.session.get('user_id', 0)
    contact = ''
    phone = ''
    address = ''
    postcode = ''

    if request.method == 'POST':
        contact = request.POST.get('contact', '')
        address = request.POST.get('address', '')
        postcode = request.POST.get('postcode', '')
        phone = request.POST.get('phone', '')

        if uid:
            user = Users.objects.get(id=uid)
            user.contact = contact
            user.address = address
            user.postcode = postcode
            user.phone = phone
            user.save()

    context = {'contact': contact, 'phone': phone, 'address': address, 'postcode': postcode, 'page_num': 1}
    return render(request, 'Users/user_center_site.html', context)

@user_decorator.login
def user_center_order(request):
    user_id = request.session.get('user_id')
    orders = OrderInfo.objects.filter(user_id=user_id)

    context = {'title': '用户中心', 'page_num': 1, 'orders': orders}
    return render(request, 'Users/user_center_order.html', context)

DayDayFruit/templates/Users/index.html
<html>
	<head></head>
	<body>
		<h1>test</h1>
		<ul>
			{% for user in users%}
				<li>{{user.uname}} -- {{user.email}}</li>
			{% endfor %}
		</ul>

		{{value|add:'2'}}

		{{list1|add:list2}}
	</body>
</html>

DayDayFruit/templates/Users/login.html
{% extends 'base_foot.html' %}

{% block title%}
<title>天天生鲜-登录</title>
{% endblock title %}

{% block js%}
<script type="text/javascript">
	$(function(){
		uname_flage = false
		pwd_flage = false

		if({{uname_err_code}}==1)
		{
			$('.user_error').html('用户名不能为空！').show();
			uname_flage = true;
		}
		else if({{uname_err_code}}==2)
		{
			$('.user_error').html('用户名长度必须大于5且小于20！').show();
			uname_flage = true;
		}
		else if({{uname_err_code}}==3)
		{
			$('.user_error').html('用户不存在!').show();
			uname_flage = true;
		};

		if({{pwd_err_code}}==1)
		{
			$('.pwd_error').html('密码错误').show();
			pwd_flage = true;
		};

		$('.name_input').blur(function(){
			check_username();
		});

		$('.pass_input').blur(function(){
			check_pwd();
		})

		$('#form_submit').submit(function(){
			check_username();
			check_pwd();

			if(uname_flage==true || pwd_flage==true)
			{
				return false;
			}
			else
			{
				return true;
			}
		});

		// 检查用户名
		function check_username(){
			username = $('.name_input').val()

			if(username == '')
			{
				$('.user_error').html('用户名不能为空！').show();
				uname_flage = true;
			}
			else
			{
				$('.user_error').hide();
				uname_flage = false;
			}
		};

		// 检查密码
		function check_pwd(){
			pwd = $('.pass_input').val()

			if(pwd == '')
			{
				$('.pwd_error').html('密码不能为空').show();
				pwd_flage = true;
			}
			else
			{
				$('.pwd_error').hide();
				pwd_flage = false;
			}
		}
	})
</script>
{% endblock js%}

{% block content%}
<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action='/user/login_handle/' id='form_submit'>
						{% csrf_token%}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" autocomplete="off" value={{uname}}>
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码" autocomplete="off">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="rember_me" value='1' checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

DayDayFruit/templates/Users/login_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{% block title%}
		这是title
	{% endblock title%}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	{% block js%}

	{% endblock js%}
</head>
<body>
	
	{% block content%}
		这是内容
	{% endblock content%}

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

DayDayFruit/templates/Users/register.html
{% extends 'base_foot.html' %}

{% block title%}
<title>天天生鲜-注册</title>
{% endblock title %}

{% block js%}
<script type="text/javascript" src="/static/js/register.js"></script>
<script type="text/javascript">
	$(function(){
		if({{uname_err_code}}==1)
		{
			$('#user_name').next().html('用户名不能为空！').show();
			error_name = true;
		}
		else if({{uname_err_code}}==2)
		{
			$('#user_name').next().html('用户名长度必须大于5且小于20！').show();
			error_name = true;
		}
		else if({{uname_err_code}}==3)
		{
			$('#user_name').next().html('用户名已经存在,请重新输入！').show();
			error_name = true;
		};

		if({{pwd_err_code}}==1)
		{
			$('#cpwd').next().html('两次输入的密码不一致').show();
			error_check_password = true;
		};

		$('#reg_form').submit(function()
		{
			if(error_name == true || error_check_password == true){
				return false;
			}
		});
	})
</script>
{% endblock js%}


{% block content%}
<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action='/user/register_handle/' id='reg_form'>
				{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="" id='submit'>
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock content %}

DayDayFruit/templates/Users/user_center_info.html
{% extends 'base.html' %}


{% block silder%}
    <div class="main_con clearfix">
			<div class="left_menu_con clearfix">
				<h3>用户中心</h3>
				<ul>
					<li><a href="/user/user_center_info/" class="active">· 个人信息</a></li>
					<li><a href="/user/user_center_order/">· 全部订单</a></li>
					<li><a href="/user/user_center_site/">· 收货地址</a></li>
				</ul>
			</div>

			{% block content %}

                <div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{uname|default:'登录后可以看到用户信息'}}</li>
							<li><span>联系方式：</span>{{phone|default:'这个家伙很懒什么都没有留下'}}</li>
							<li><span>联系地址：</span>{{address|default:'这个家伙很懒什么都没有留下'}}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for good in goods_list %}
                        	<li>
                                <a href="/goods/detail{{ good.vtype }}/{{ good.vindex }}/"><img src="/static/{{ good.vpic }}"></a>
                                <h4><a href="/goods/detail/{{ good.vtype }}/{{ good.vindex }}/">{{ good.vtitle }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ good.vprice }}</span>
                                    <span class="unit">{{ good.vprice }}/{{ good.vunit }}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}
				    </ul>
		        </div>
		</div>
            {% endblock content%}
</div>
{% endblock silder%}

DayDayFruit/templates/Users/user_center_order.html
{% extends 'base.html' %}

{% block silder %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/user_center_info/">· 个人信息</a></li>
				<li><a href="/user/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/user/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>

        {% block content%}
		<div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>

            {% for order in orders %}
                <ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.odate }}</li>
					<li class="col02">订单号：{{ order.oid }}</li>
                    {% if order.oIsPay == 0 %}
					    <li class="col02 stress">未支付</li>
                    {% else %}
                        <li class="col02 stress">已支付</li>
                    {% endif %}
				</ul>

                <table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for detail in order.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ detail.goods.gpic }}"></li>
									<li class="col02">{{ detail.goods.gtitle }}<em>{{ detail.goods.gprice }}元/{{ detail.goods.unit }}</em></li>
									<li class="col03">{{ detail.count }}</li>
									<li class="col04">{{ detail.goods.gprice }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.ototal }}元</td>
                            {% if order.oIsPay == 0 %}
							    <td width="15%">待付款</td>
                                <td width="15%"><a href="/order/paymoney/{{ order.oid }}" class="oper_btn">去付款</a></td>
                            {% else %}
                                <td width="15%">已付款</td>
                                <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>
            {% endfor %}

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>

            {% endblock content %}
	</div>
{% endblock silder %}

DayDayFruit/templates/Users/user_center_site.html
{% extends 'base.html' %}

{% block silder %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/user/user_center_info/" class="active">· 个人信息</a></li>
                <li><a href="/user/user_center_order/">· 全部订单</a></li>
                <li><a href="/user/user_center_site/">· 收货地址</a></li>
            </ul>
        </div>
    {% block content%}
            <div class="right_content clearfix">
                    <h3 class="common_title2">收货地址</h3>
                    <div class="site_con">
                        <dl>
                            <dt>当前地址：</dt>
                            <dd>{{address}} （{{contact}} 收） {{phone}}</dd>
                        </dl>
                    </div>
                    <h3 class="common_title2">编辑地址</h3>
                    <div class="site_con">
                        <form method="post" action='/user/user_center_site_handle/'>
                          {% csrf_token %}
                            <div class="form_group">
                                <label>收件人：</label>
                                <input type="text" name="contact" value={{contact}}>
                            </div>
                            <div class="form_group form_group2">
                                <label>详细地址：</label>
                                <textarea class="site_area" name='address'>{{address}}</textarea>
                            </div>
                            <div class="form_group">
                                <label>邮编：</label>
                                <input type="text" name="postcode" value={{postcode}}>
                            </div>
                            <div class="form_group">
                                <label>手机：</label>
                                <input type="text" name="phone" value={{phone}}>
                            </div>

                            <input type="submit" name="" value="提交" class="info_submit">
                        </form>
                    </div>
            </div>
    {% endblock content%}
    </div>
{% endblock silder %}